//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jellyfin.Resources.Localisations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jellyfin.Resources.Localisations.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jellyfin-For-Xbox.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string Common_Abort {
            get {
                return ResourceManager.GetString("Common.Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Common_Ok {
            get {
                return ResourceManager.GetString("Common.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app encountered an unexpected Error. Do you want to attempt to upload the Logfile to the server?.
        /// </summary>
        public static string Dialog_Crash_Body {
            get {
                return ResourceManager.GetString("Dialog.Crash.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Application has encountered an unexpected issue.
        /// </summary>
        public static string Dialog_Crash_Only_Body {
            get {
                return ResourceManager.GetString("Dialog.Crash.Only.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Dialog_Crash_Title {
            get {
                return ResourceManager.GetString("Dialog.Crash.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not disable layout scaling. This application is not designed to run on a desktop PC but only on an Xbox device. 
        ///
        ///You might encounter bugs when running on a PC..
        /// </summary>
        public static string Dialog_Warning_LayoutScaling {
            get {
                return ResourceManager.GetString("Dialog.Warning.LayoutScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string OnBoarding_Connect_Text {
            get {
                return ResourceManager.GetString("OnBoarding.Connect.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Jellyfin Server..
        /// </summary>
        public static string OnBoarding_ConnectTo_Text {
            get {
                return ResourceManager.GetString("OnBoarding.ConnectTo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No local servers found..
        /// </summary>
        public static string OnBoarding_ServerDiscovery_Empty_Text {
            get {
                return ResourceManager.GetString("OnBoarding.ServerDiscovery.Empty.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Servers..
        /// </summary>
        public static string OnBoarding_ServerDiscovery_Header_Text {
            get {
                return ResourceManager.GetString("OnBoarding.ServerDiscovery.Header.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to connect to:.
        /// </summary>
        public static string OnBoarding_ServerList_Error_Text {
            get {
                return ResourceManager.GetString("OnBoarding.ServerList.Error.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to connect to:.
        /// </summary>
        public static string OnBoarding_ServerLookup_Header_Text {
            get {
                return ResourceManager.GetString("OnBoarding.ServerLookup.Header.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: 192.168.1.100:8096 or demo.jellyfin.org.
        /// </summary>
        public static string OnBoarding_ServerUri_Placeholder {
            get {
                return ResourceManager.GetString("OnBoarding.ServerUri.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error validating server response..
        /// </summary>
        public static string ServerLookupValidation_Error_Fallback_Text {
            get {
                return ResourceManager.GetString("ServerLookupValidation.Error.Fallback.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception parsing server response: {0}.
        /// </summary>
        public static string ServerLookupValidation_Error_General_Text {
            get {
                return ResourceManager.GetString("ServerLookupValidation.Error.General.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It does not seem that the requested Url runs a Jellyfin server..
        /// </summary>
        public static string ServerLookupValidation_Error_NoServerDetected_Text {
            get {
                return ResourceManager.GetString("ServerLookupValidation.Error.NoServerDetected.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductName &apos;{0}&apos; does not match expected &apos;{1}&apos;..
        /// </summary>
        public static string ServerLookupValidation_Error_ProductName_Text {
            get {
                return ResourceManager.GetString("ServerLookupValidation.Error.ProductName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid server version format: &apos;{0}&apos;.
        /// </summary>
        public static string ServerLookupValidation_Error_ServerVersion_Invalid_Text {
            get {
                return ResourceManager.GetString("ServerLookupValidation.Error.ServerVersion.Invalid.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum supported server version is {0}, but the server is running {1}..
        /// </summary>
        public static string ServerLookupValidation_Error_ServerVersion_MinimumSupported_Text {
            get {
                return ResourceManager.GetString("ServerLookupValidation.Error.ServerVersion.MinimumSupported.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the server at &quot;{0}&quot;. Status code: {1} - {2}.
        /// </summary>
        public static string ServerValidation_Error_Rejected_Text {
            get {
                return ResourceManager.GetString("ServerValidation.Error.Rejected.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Logfile.
        /// </summary>
        public static string Settings_UploadLogfile {
            get {
                return ResourceManager.GetString("Settings.UploadLogfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while uploading the current logfile. Please try again..
        /// </summary>
        public static string Settings_UploadLogfile_Failure_Text {
            get {
                return ResourceManager.GetString("Settings.UploadLogfile.Failure.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current logfile has been uploaded to your Jellyfin server..
        /// </summary>
        public static string Settings_UploadLogfile_Success_Text {
            get {
                return ResourceManager.GetString("Settings.UploadLogfile.Success.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the display refresh rate to the media refresh rate.
        /// </summary>
        public static string Settings_Values_AutoRefresh_Text {
            get {
                return ResourceManager.GetString("Settings.Values.AutoRefresh.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto display refresh rate is not supported on this device..
        /// </summary>
        public static string Settings_Values_AutoRefresh_Unsupported_Text {
            get {
                return ResourceManager.GetString("Settings.Values.AutoRefresh.Unsupported.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the display resolution to the media resolution.
        /// </summary>
        public static string Settings_Values_AutoResolution_Text {
            get {
                return ResourceManager.GetString("Settings.Values.AutoResolution.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display resolution is not supported on this device..
        /// </summary>
        public static string Settings_Values_AutoResolution_Unsupported_Text {
            get {
                return ResourceManager.GetString("Settings.Values.AutoResolution.Unsupported.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the server at &quot;{0}&quot;. Error:
        ///
        ///{1}.
        /// </summary>
        public static string UrlValidation_Error_General_Text {
            get {
                return ResourceManager.GetString("UrlValidation.Error.General.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a server address..
        /// </summary>
        public static string UrlValidation_Error_NoInput_Text {
            get {
                return ResourceManager.GetString("UrlValidation.Error.NoInput.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request timed out. Please check your network connection and try again..
        /// </summary>
        public static string UrlValidation_Error_Timeout_Text {
            get {
                return ResourceManager.GetString("UrlValidation.Error.Timeout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not initialize WebView..
        /// </summary>
        public static string WebView_Error_InitializationFailed_Text {
            get {
                return ResourceManager.GetString("WebView.Error.InitializationFailed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation failed. Reason:
        ///
        ///{0}.
        /// </summary>
        public static string WebView_Error_NavigationFailed_Text {
            get {
                return ResourceManager.GetString("WebView.Error.NavigationFailed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Jellyfin server {0}  is currently not available: 
        ///
        /// {1}.
        /// </summary>
        public static string WebView_Error_ValidationFailed_Text {
            get {
                return ResourceManager.GetString("WebView.Error.ValidationFailed.Text", resourceCulture);
            }
        }
    }
}
